<h1>Faça seu login</h1>
<?php echo $this->form()->openTag($form); ?>
<div class="form_element">
    <?php echo $this->formRow($form->get('username')); ?>
</div>
<div class="form_element">
    <?php echo $this->formRow($form->get('password')); ?>
</div>
<?php echo $this->formElement($form->get('send')) ?>

<?php if ($messageError): ?>
<div class="row">
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span>
        </button>
        <strong>Erro!</strong> <?= $messageError; ?>
    </div>
</div>
<?php endif; ?>

<?php echo $this->form()->closeTag() ?>