<div class="row">
    <a class="btn btn-success pull-left" href="/beer/create"><i class="glyphicon glyphicon-plus-sign"></i> Nova Cerveja</a>
    <a class="btn btn-primary pull-right" href="/auth/logout"><i class="glyphicon glyphicon-home"></i> Sair</a>
    
</div>
<br>
<div class="row">
<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nome</th>
            <th>Estilo</th>
            <th>Imagem</th>
            <th>Editar</th>
            <th>Apagar</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->beers as $beer): ?>
            <tr>
                <th scope="row"><?php echo $beer['id']; ?></th>
                <td><?php echo $beer['name']; ?></td>
                <td><?php echo $beer['style']; ?></td>
                <td><img src="<?php echo $beer['img']; ?>"></td>
                <td style="text-align: center; width: 20px;"><a class="btn btn-warning" href="/beer/edit/<?php echo $beer['id']; ?>"><i class="glyphicon glyphicon-pencil"></i></a></td>
                <td style="text-align: center; width: 20px;"><a class="btn btn-danger" href="/beer/delete/<?php echo $beer['id']; ?>"><i class="glyphicon glyphicon-trash"></i></a></td>
            </tr>
<?php endforeach; ?>
    </tbody>
</table>
</div>